from dataclasses import asdict, dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class Capability:
    id: str
    name: str
    description: str
    risk_level: str
    requires_approval: bool
    tool_ids: List[str]
    default_enabled: bool = True
    can_run_unattended: bool = False

    def to_dict(self) -> Dict[str, object]:
        return asdict(self)


CAPABILITIES: Dict[str, Capability] = {
    "browser_control": Capability(
        id="browser_control",
        name="Browser Control",
        description="Open websites and interact with browser pages.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["computer_use", "mcp.playwright"],
        can_run_unattended=True,
    ),
    "screen_read": Capability(
        id="screen_read",
        name="Screen Read",
        description="Read screenshots, page state, or app-visible content.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["screenshot", "ocr", "computer_use.screenshot"],
        can_run_unattended=True,
    ),
    "mouse_control": Capability(
        id="mouse_control",
        name="Mouse Control",
        description="Move, click, drag, or scroll with the pointer.",
        risk_level="medium",
        requires_approval=True,
        tool_ids=["computer_use.click", "desktop.mouse"],
    ),
    "keyboard_input": Capability(
        id="keyboard_input",
        name="Keyboard Input",
        description="Type text or press keys in apps and websites.",
        risk_level="medium",
        requires_approval=True,
        tool_ids=["computer_use.fill", "computer_use.press", "desktop.keyboard"],
    ),
    "file_read": Capability(
        id="file_read",
        name="File Read",
        description="Read local files inside approved roots.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["mcp.filesystem.read", "computer_service.search", "read_workspace_file"],
        can_run_unattended=True,
    ),
    "code_analysis": Capability(
        id="code_analysis",
        name="Code Analysis",
        description="Search symbols, read workspace source, build call graphs, and run linters.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "search_code_symbols",
            "get_code_call_graph",
            "read_workspace_file",
            "search_code_text",
            "init_codegraph_index",
            "run_python_linter",
        ],
        can_run_unattended=True,
    ),
    "file_write": Capability(
        id="file_write",
        name="File Write",
        description="Create or modify local files.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["mcp.filesystem.write", "mcp.filesystem.edit"],
    ),
    "file_delete": Capability(
        id="file_delete",
        name="File Delete",
        description="Delete files or folders.",
        risk_level="critical",
        requires_approval=True,
        tool_ids=["mcp.filesystem.delete"],
    ),
    "app_launch": Capability(
        id="app_launch",
        name="App Launch",
        description="Open local desktop applications.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["desktop.app_launch"],
    ),
    "shell_command": Capability(
        id="shell_command",
        name="Shell Command",
        description="Run terminal commands on the local computer.",
        risk_level="critical",
        requires_approval=True,
        tool_ids=["terminal", "desktop.shell"],
    ),
    "platform_message": Capability(
        id="platform_message",
        name="Platform Message",
        description="Send messages through connected platforms.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["connector.message", "feishu", "discord", "dingtalk", "wechat", "qq"],
    ),
    "platform_read": Capability(
        id="platform_read",
        name="Platform Read",
        description="Read messages, documents, calendar events, or records from connected platforms.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["connector.read", "feishu.read", "discord.read", "dingtalk.read", "wechat", "qq"],
        can_run_unattended=True,
    ),
    "platform_publish": Capability(
        id="platform_publish",
        name="Platform Publish",
        description="Publish content to social or content platforms.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["publisher_tools", "connector.publish"],
    ),
    "media_generate": Capability(
        id="media_generate",
        name="Media Generate",
        description="Generate images, audio, or video assets.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["image_tools", "video_tools", "audio_tools"],
        can_run_unattended=True,
    ),
    "media_pipeline_gate": Capability(
        id="media_pipeline_gate",
        name="Media Pipeline Human Gate",
        description="Human approval for storyboard, key visuals, video segments, or publish copy in the media pipeline.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["media_pipeline.step_gate"],
        can_run_unattended=False,
    ),
    "creative_app_script": Capability(
        id="creative_app_script",
        name="Creative App Script",
        description=(
            "Run scripts or batch automation in Blender, Unity, Unreal, Photoshop. "
            "Use GET /creative-apps/profiles and POST /creative-apps/plan for CLI templates; "
            "execution requires local computer shell/launch with approval."
        ),
        risk_level="high",
        requires_approval=True,
        tool_ids=["blender.script", "unity.script", "unreal.script", "photoshop.script", "creative_apps.plan"],
    ),
    "native_desktop_control": Capability(
        id="native_desktop_control",
        name="Native Desktop Control",
        description=(
            "Native GUI automation: capture screen, mouse, keyboard for any desktop app. "
            "Use POST /native-use/run or run_native_desktop_task tool."
        ),
        risk_level="high",
        requires_approval=True,
        tool_ids=["native_use.run", "desktop.native"],
        can_run_unattended=False,
    ),
    "dev_git_ops": Capability(
        id="dev_git_ops",
        name="Dev Git Operations",
        description="Inspect git remotes, branches, and SSH configuration.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["programmer_tools.git_inspect", "programmer_tools.git_status"],
        can_run_unattended=True,
    ),
    "dev_infra_manage": Capability(
        id="dev_infra_manage",
        name="Infrastructure Management",
        description="Probe and manage Redis, MySQL, MongoDB, etcd, Consul, NSQ, and similar services.",
        risk_level="high",
        requires_approval=True,
        tool_ids=[
            "programmer_tools.scan_infra",
            "programmer_tools.check_infra",
            "programmer_tools.infra_start",
            "programmer_tools.infra_stop",
        ],
    ),
    "pm_market_research": Capability(
        id="pm_market_research",
        name="PM Market Research",
        description="Market insight and competitor landscape analysis via web search and trend signals.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "collect_market_signals",
            "list_product_manager_recipes",
            "run_product_manager_recipe",
            "search_web",
            "skills_list",
            "skill_view",
        ],
        can_run_unattended=True,
    ),
    "pm_product_analysis": Capability(
        id="pm_product_analysis",
        name="PM Product Analysis",
        description="Diagnose and optimize products; Discovery, roadmap, user stories via PM skills.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "collect_market_signals",
            "list_product_manager_recipes",
            "run_product_manager_recipe",
            "search_web",
            "skills_list",
            "skill_view",
        ],
        can_run_unattended=True,
    ),
    "pm_idea_generation": Capability(
        id="pm_idea_generation",
        name="PM Idea Generation",
        description="Generate structured product ideas and MVP directions from market signals.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "collect_market_signals",
            "list_product_manager_recipes",
            "run_product_manager_recipe",
            "search_web",
            "skills_list",
            "skill_view",
        ],
        can_run_unattended=True,
    ),
    "ga_visual_design": Capability(
        id="ga_visual_design",
        name="Game Art Visual Design",
        description="Visual style guides, UI art guidelines and competitor visual analysis.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["game_art_tools.collect_game_art_signals", "game_art_tools.run_game_art_recipe"],
        can_run_unattended=True,
    ),
    "ga_character_scene": Capability(
        id="ga_character_scene",
        name="Game Art Character Scene",
        description="Character design briefs and scene concept art specifications.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["game_art_tools.run_game_art_recipe"],
        can_run_unattended=True,
    ),
    "gd_concept_system": Capability(
        id="gd_concept_system",
        name="Game Design Concept System",
        description="Concept pitches, core loops and system design documents.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["game_design_tools.collect_game_design_signals", "game_design_tools.run_game_design_recipe"],
        can_run_unattended=True,
    ),
    "gd_level_content": Capability(
        id="gd_level_content",
        name="Game Design Level Content",
        description="Level and content planning with difficulty curves.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["game_design_tools.run_game_design_recipe"],
        can_run_unattended=True,
    ),
    "gd_narrative_balance": Capability(
        id="gd_narrative_balance",
        name="Game Design Narrative Balance",
        description="Narrative outlines and numeric balance frameworks.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["game_design_tools.run_game_design_recipe"],
        can_run_unattended=True,
    ),
    "legal_case_research": Capability(
        id="legal_case_research",
        name="Legal Case Research",
        description="Research judicial cases, guiding cases and enforcement signals for authoritative interpretation.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["legal_tools.collect_signals", "legal_tools.case_research"],
        can_run_unattended=True,
    ),
    "legal_compliance_audit": Capability(
        id="legal_compliance_audit",
        name="Legal Compliance Audit",
        description="Assess corporate compliance risks across governance, labor, tax and data protection.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["legal_tools.compliance_audit"],
        can_run_unattended=True,
    ),
    "legal_regulation_interpret": Capability(
        id="legal_regulation_interpret",
        description="Interpret laws, regulations and policies for business and personal economic activities.",
        name="Legal Regulation Interpretation",
        risk_level="low",
        requires_approval=False,
        tool_ids=["legal_tools.regulation_interpret"],
        can_run_unattended=True,
    ),
    "legal_contract_review": Capability(
        id="legal_contract_review",
        name="Legal Contract Review",
        description="Identify high-risk clauses in investment, labor, procurement and partnership contracts.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["legal_tools.contract_review"],
        can_run_unattended=True,
    ),
    "legal_finance_advisory": Capability(
        id="legal_finance_advisory",
        name="Legal Finance Advisory",
        description="Advise on tax, investment, settlement and personal economic dispute legal boundaries.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["legal_tools.finance_legal"],
        can_run_unattended=True,
    ),
    "procurement_vendor_eval": Capability(
        id="procurement_vendor_eval",
        name="Procurement Vendor Evaluation",
        description="Due diligence on vendors across delivery, quality, finance and compliance.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.collect_signals", "procurement_tools.vendor_evaluate"],
        can_run_unattended=True,
    ),
    "procurement_rfq": Capability(
        id="procurement_rfq",
        name="Procurement RFQ Drafting",
        description="Draft structured RFQ documents with specs, scoring and commercial terms.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.rfq_draft"],
        can_run_unattended=True,
    ),
    "procurement_quote_compare": Capability(
        id="procurement_quote_compare",
        name="Procurement Quote Comparison",
        description="Compare vendor quotes with TCO analysis and negotiation guidance.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.quote_compare"],
        can_run_unattended=True,
    ),
    "procurement_contract_review": Capability(
        id="procurement_contract_review",
        name="Procurement Contract Review",
        description="Review procurement contract clauses for payment, delivery and liability risks.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.contract_review"],
        can_run_unattended=True,
    ),
    "procurement_cost_optimize": Capability(
        id="procurement_cost_optimize",
        name="Procurement Cost Optimization",
        description="Spend analysis and cost reduction strategies for purchase categories.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.cost_optimize"],
        can_run_unattended=True,
    ),
    "procurement_sourcing": Capability(
        id="procurement_sourcing",
        name="Procurement Sourcing Strategy",
        description="Category sourcing strategy, supplier pool and risk diversification.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["procurement_tools.sourcing_strategy"],
        can_run_unattended=True,
    ),
    "ad_strategy_planning": Capability(
        id="ad_strategy_planning",
        name="Ad Strategy Planning",
        description="Multi-channel ad strategy, KPI framework and campaign pacing.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["ad_campaign_tools.collect_signals", "ad_campaign_tools.strategy_plan"],
        can_run_unattended=True,
    ),
    "ad_creative_generation": Capability(
        id="ad_creative_generation",
        name="Ad Creative Generation",
        description="Generate ad copy variants with headlines, body text and CTA for A/B testing.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["ad_campaign_tools.creative_copy"],
        can_run_unattended=True,
    ),
    "ad_audience_analysis": Capability(
        id="ad_audience_analysis",
        name="Ad Audience Analysis",
        description="Audience segmentation, targeting tags and exclusion strategies.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["ad_campaign_tools.audience_analyze"],
        can_run_unattended=True,
    ),
    "ad_budget_allocation": Capability(
        id="ad_budget_allocation",
        name="Ad Budget Allocation",
        description="Budget split across channels with pacing and ROI assumptions.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["ad_campaign_tools.budget_allocate"],
        can_run_unattended=True,
    ),
    "ad_performance_review": Capability(
        id="ad_performance_review",
        name="Ad Performance Review",
        description="Campaign post-mortem, diagnostics and optimization recommendations.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["ad_campaign_tools.report_review"],
        can_run_unattended=True,
    ),
    "bp_outreach_draft": Capability(
        id="bp_outreach_draft",
        name="Partnership Outreach Draft",
        description="Draft cold outreach emails and follow-up sequences for BD.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["business_partnership_tools.collect_signals", "business_partnership_tools.outreach"],
        can_run_unattended=True,
    ),
    "bp_proposal_generation": Capability(
        id="bp_proposal_generation",
        name="Partnership Proposal Generation",
        description="Structured business partnership proposals with milestones and ROI.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["business_partnership_tools.proposal"],
        can_run_unattended=True,
    ),
    "bp_contract_review": Capability(
        id="bp_contract_review",
        name="Partnership Contract Review",
        description="Business-oriented clause review memo (not formal legal advice).",
        risk_level="medium",
        requires_approval=False,
        tool_ids=["business_partnership_tools.contract_review"],
        can_run_unattended=True,
    ),
    "bp_partner_evaluation": Capability(
        id="bp_partner_evaluation",
        name="Partner Evaluation",
        description="Evaluate potential partners on fit, resources, brand and execution risk.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["business_partnership_tools.partner_evaluate"],
        can_run_unattended=True,
    ),
    "bp_pipeline_planning": Capability(
        id="bp_pipeline_planning",
        name="BD Pipeline Planning",
        description="Partnership funnel stages, targets and weekly BD actions.",
        risk_level="low",
        requires_approval=False,
        tool_ids=["business_partnership_tools.pipeline_plan"],
        can_run_unattended=True,
    ),
    "system_install": Capability(
        id="system_install",
        name="System Install",
        description="Install or uninstall desktop applications via brew/winget.",
        risk_level="critical",
        requires_approval=True,
        tool_ids=["system_tools.install", "system_tools.uninstall"],
    ),
    "system_network_fix": Capability(
        id="system_network_fix",
        name="System Network Fix",
        description="Diagnose and repair network connectivity issues.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["system_tools.network"],
    ),
    "system_file_organize": Capability(
        id="system_file_organize",
        name="System File Organize",
        description="Preview and apply file organization plans within approved folders.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["system_tools.organize"],
    ),
    "system_env_config": Capability(
        id="system_env_config",
        name="System Environment Config",
        description="Configure development tools and shell environment.",
        risk_level="high",
        requires_approval=True,
        tool_ids=["system_tools.env"],
    ),
    "memory_write": Capability(
        id="memory_write",
        name="Memory Write",
        description="Save long-term user or project memory.",
        risk_level="medium",
        requires_approval=True,
        tool_ids=["memory_tools.save", "mcp.memory"],
    ),
    "short_drama_production": Capability(
        id="short_drama_production",
        name="AI Short Drama Production",
        description="End-to-end AI short drama: script, storyboard, scene generation, voiceover, subtitle and final assembly.",
        risk_level="medium",
        requires_approval=False,
        tool_ids=[
            "short_drama_tools.list_recipes",
            "short_drama_tools.run_recipe",
            "script_tools.generate_script",
            "image_tools.generate_image",
            "video_tools.generate_video",
            "audio_tools.generate_speech",
            "subtitle_tools.generate_subtitles",
        ],
        can_run_unattended=True,
    ),
    "podcast_production": Capability(
        id="podcast_production",
        name="AI Podcast Production",
        description="AI podcast assistant: topic planning, script writing, host dialogues, cover art and publishing.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "podcast_tools.list_recipes",
            "podcast_tools.run_recipe",
            "copywriting_tools.generate_copywriting",
            "script_tools.generate_script",
            "image_tools.generate_image",
            "audio_tools.generate_speech",
        ],
        can_run_unattended=True,
    ),
    "music_production": Capability(
        id="music_production",
        name="AI Music Production",
        description="Text-to-music and lyrics-to-music generation with style, mood, structure and duration control.",
        risk_level="low",
        requires_approval=False,
        tool_ids=[
            "music_tools.list_recipes",
            "music_tools.run_recipe",
            "music_tools.generate_music",
        ],
        can_run_unattended=True,
    ),
}


def list_capabilities() -> List[Dict[str, object]]:
    return [capability.to_dict() for capability in CAPABILITIES.values()]


def get_capability(capability_id: str) -> Optional[Capability]:
    return CAPABILITIES.get(capability_id)


def require_capability(capability_id: str) -> Capability:
    capability = get_capability(capability_id)
    if capability is None:
        raise KeyError(f"Unknown capability: {capability_id}")
    return capability


def requires_approval(capability_id: str) -> bool:
    return require_capability(capability_id).requires_approval